site_name: Docs | IMPulse
theme:
  name: readthedocs

extra:
  analytics:
    provider: google
    property: G-LL3R99ZZGW

nav:
- index.md
- Instant Messaging Apps:
  - slack.md
  - mattermost.md
- Installation process:
  - get.md
  - Configure:
    - apps.md
    - alertmanager.md
    - impulse.md
  - run.md
- Maintenance:
  - upgrade.md
  # - Exceptions:
  #   - exceptions/chain-undefined.md
  #   - exceptions/status-unknown.md
  #   - exceptions/user-not_found.md
  #   - exceptions/webhook-domain_non_existent.md
  #   - exceptions/webhook-undefined.md
  #   - exceptions/webhook_responce-above_400.md
- About:
  - concepts.md
  - templates.md
  - versioning.md
  - webhooks.md
